version: '3.7'
services:
  client:
    env_file:
      - .env
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        app_env: ${APP_ENV}
    volumes:
      - ./client/src:/client/src
    ports:
      - "3000:3000"
